ACTIVIDAD 2.2

In [36]:
##INSTALAR LIBRERIAS
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.3.2)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.10.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.3.2)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (2.3.2)
Requirement already satisfied: pandas>=1.2 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (2.3.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (3.10.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from openpyxl) (2.0.0)

In [37]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [38]:
#Convertir en dataframe
df= pd.read_csv("listings.csv")
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2539,https://www.airbnb.com/rooms/2539,20250617032754,2025-06-17,city scrape,Superfast Wi-Fi. Clean & quiet home by the park,"Bright, serene room in a renovated apartment h...",Close to Prospect Park and Historic Ditmas Park,https://a0.muscache.com/pictures/hosting/Hosti...,2787,...,5.0,4.75,4.88,NaN,f,6,1,5,0,0.08
1,2595,https://www.airbnb.com/rooms/2595,20250617032754,2025-06-17,city scrape,Skylit Midtown Manhattan Spacious Studio,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,https://a0.muscache.com/pictures/hosting/Hosti...,2845,...,4.8,4.81,4.40,NaN,f,3,3,0,0,0.26
2,5136,https://www.airbnb.com/rooms/5136,20250617032754,2025-06-17,city scrape,Spacious Family Friendly Duplex w/ Patio + Yard,"We welcome you to stay in our lovely 2 br, 130...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,7378,...,5.0,4.75,4.75,NaN,t,1,1,0,0,0.03
3,6848,https://www.airbnb.com/rooms/6848,20250617032754,2025-06-17,city scrape,Only 2 stops to Manhattan studio,Comfortable studio apartment with super comfor...,NaN,https://a0.muscache.com/pictures/e4f031a7-f146...,15991,...,4.8,4.69,4.58,NaN,f,1,1,0,0,1.00
4,6872,https://www.airbnb.com/rooms/6872,20250617032754,2025-06-17,previous scrape,Uptown Sanctuary w/ Private Bath (Month to Month),This charming distancing-friendly month-to-mon...,This sweet Harlem sanctuary is a 10-20 minute ...,https://a0.muscache.com/pictures/miso/Hosting-...,16104,...,5.0,5.00,5.00,NaN,f,2,0,2,0,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36317,1444361816139266163,https://www.airbnb.com/rooms/1444361816139266163,20250617032754,2025-06-17,city scrape,Soho LES,Book this centrally located home for groups an...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,408918750,...,NaN,NaN,NaN,NaN,t,4,4,0,0,NaN
36318,1444367137899199563,https://www.airbnb.com/rooms/1444367137899199563,20250617032754,2025-06-17,city scrape,Park & Pool Adjacent Loft Studio,"Situated next to Brooklyn Navy Yard, between D...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,2076525,...,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN
36319,1444466789913170608,https://www.airbnb.com/rooms/1444466789913170608,20250617032754,2025-06-17,city scrape,"Peaceful Room, Big Comfy Bed","Peaceful, sunlit bedroom in a friendly, tree-t...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,42088828,...,NaN,NaN,NaN,NaN,f,2,0,2,0,NaN
36320,1444497972042807274,https://www.airbnb.com/rooms/1444497972042807274,20250617032754,2025-06-17,city scrape,"Steps from the Empire State, Iconic Views, 2 Beds",Welcome to your dream Manhattan escape — a stu...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,677540330,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
36321,1444533606768940303,https://www.airbnb.com/rooms/1444533606768940303,20250617032754,2025-06-17,city scrape,2BR/Brooklyn: Private Backyard,Spacious 2BR Brooklyn home in beautiful Bed-St...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,10931359,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [8]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36322 entries, 0 to 36321
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            36322 non-null  int64
 1   listing_url                                   36322 non-null  object
 2   scrape_id                                     36322 non-null  int64
 3   last_scraped                                  36322 non-null  object
 4   source                                        36322 non-null  object
 5   name                                          36320 non-null  object
 6   description                                   35374 non-null  object
 7   neighborhood_overview                         19084 non-null  object
 8   picture_url                                   36322 non-null  object
 9   host_id                                       36322 non-null  int64
 10  host_url                                      36322 non-null  object
 11  host_name                                     36307 non-null  object
 12  host_since                                    36307 non-null  object
 13  host_location                                 28913 non-null  object
 14  host_about                                    20956 non-null  object
 15  host_response_time                            21550 non-null  object
 16  host_response_rate                            21550 non-null  object
 17  host_acceptance_rate                          21720 non-null  object
 18  host_is_superhost                             35830 non-null  object
 19  host_thumbnail_url                            36307 non-null  object
 20  host_picture_url                              36307 non-null  object
 21  host_neighbourhood                            29034 non-null  object
 22  host_listings_count                           36307 non-null  float64
 23  host_total_listings_count                     36307 non-null  float64
 24  host_verifications                            36307 non-null  object
 25  host_has_profile_pic                          36307 non-null  object
 26  host_identity_verified                        36307 non-null  object
 27  neighbourhood                                 19085 non-null  object
 28  neighbourhood_cleansed                        36322 non-null  object
 29  neighbourhood_group_cleansed                  36322 non-null  object
 30  latitude                                      36322 non-null  float64
 31  longitude                                     36322 non-null  float64
 32  property_type                                 36322 non-null  object
 33  room_type                                     36322 non-null  object
 34  accommodates                                  36322 non-null  int64
 35  bathrooms                                     21682 non-null  float64
 36  bathrooms_text                                36286 non-null  object
 37  bedrooms                                      30274 non-null  float64
 38  beds                                          21620 non-null  float64
 39  amenities                                     36322 non-null  object
 40  price                                         21459 non-null  object
 41  minimum_nights                                36322 non-null  int64
 42  maximum_nights                                36322 non-null  int64
 43  minimum_minimum_nights                        36322 non-null  int64
 44  maximum_minimum_nights                        36322 non-null  int64
 45  minimum_maximum_nights                        36322 non-null  int64
 46  maximum_maximum_nights                        36322 non-null  int64
 47  minimum_nights_avg_ntm                        36322 non-null  float64
 48  maximum_nights_avg_ntm                        36322 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              30705 non-null  object
 51  availability_30                               36322 non-null  int64
 52  availability_60                               36322 non-null  int64
 53  availability_90                               36322 non-null  int64
 54  availability_365                              36322 non-null  int64
 55  calendar_last_scraped                         36322 non-null  object
 56  number_of_reviews                             36322 non-null  int64
 57  number_of_reviews_ltm                         36322 non-null  int64
 58  number_of_reviews_l30d                        36322 non-null  int64
 59  availability_eoy                              36322 non-null  int64
 60  number_of_reviews_ly                          36322 non-null  int64
 61  estimated_occupancy_l365d                     36322 non-null  int64
 62  estimated_revenue_l365d                       21459 non-null  float64
 63  first_review                                  25171 non-null  object
 64  last_review                                   25171 non-null  object
 65  review_scores_rating                          25171 non-null  float64
 66  review_scores_accuracy                        25161 non-null  float64
 67  review_scores_cleanliness                     25170 non-null  float64
 68  review_scores_checkin                         25157 non-null  float64
 69  review_scores_communication                   25165 non-null  float64
 70  review_scores_location                        25154 non-null  float64
 71  review_scores_value                           25155 non-null  float64
 72  license                                       5329 non-null   object
 73  instant_bookable                              36322 non-null  object
 74  calculated_host_listings_count                36322 non-null  int64
 75  calculated_host_listings_count_entire_homes   36322 non-null  int64
 76  calculated_host_listings_count_private_rooms  36322 non-null  int64
 77  calculated_host_listings_count_shared_rooms   36322 non-null  int64
 78  reviews_per_month                             25171 non-null  float64
dtypes: float64(19), int64(24), object(36)
memory usage: 21.9+ MB

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2539,https://www.airbnb.com/rooms/2539,20250617032754,2025-06-17,city scrape,Superfast Wi-Fi. Clean & quiet home by the park,"Bright, serene room in a renovated apartment h...",Close to Prospect Park and Historic Ditmas Park,https://a0.muscache.com/pictures/hosting/Hosti...,2787,...,5.0,4.75,4.88,NaN,f,6,1,5,0,0.08
1,2595,https://www.airbnb.com/rooms/2595,20250617032754,2025-06-17,city scrape,Skylit Midtown Manhattan Spacious Studio,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,https://a0.muscache.com/pictures/hosting/Hosti...,2845,...,4.8,4.81,4.40,NaN,f,3,3,0,0,0.26
2,5136,https://www.airbnb.com/rooms/5136,20250617032754,2025-06-17,city scrape,Spacious Family Friendly Duplex w/ Patio + Yard,"We welcome you to stay in our lovely 2 br, 130...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,7378,...,5.0,4.75,4.75,NaN,t,1,1,0,0,0.03
3,6848,https://www.airbnb.com/rooms/6848,20250617032754,2025-06-17,city scrape,Only 2 stops to Manhattan studio,Comfortable studio apartment with super comfor...,NaN,https://a0.muscache.com/pictures/e4f031a7-f146...,15991,...,4.8,4.69,4.58,NaN,f,1,1,0,0,1.00
4,6872,https://www.airbnb.com/rooms/6872,20250617032754,2025-06-17,previous scrape,Uptown Sanctuary w/ Private Bath (Month to Month),This charming distancing-friendly month-to-mon...,This sweet Harlem sanctuary is a 10-20 minute ...,https://a0.muscache.com/pictures/miso/Hosting-...,16104,...,5.0,5.00,5.00,NaN,f,2,0,2,0,0.03

In [9]:
#a) Los registros de 5 “host name”  diferentes
filtro=df["name"].head()
filtro

0     Superfast Wi-Fi.  Clean & quiet home by the park
1             Skylit Midtown Manhattan Spacious Studio
2      Spacious Family Friendly Duplex w/ Patio + Yard
3                     Only 2 stops to Manhattan studio
4    Uptown Sanctuary w/ Private Bath (Month to Month)
Name: name, dtype: object

In [19]:
revision1 = df.groupby("name").size().reset_index(name='counts')
revision1

                                                    name  counts
0           ! Hamilton Studio. priv bathrm. near subways       1
1      ! Hamilton Suite. private. 2bdrm + 2bth + kitchen       1
2      !!! Designer room in NYC!!! 12 min to Time Square       1
3                    !!Studio next to Empire State Bldg.       1
4                       !Furnished One Bed Apt W/AC UWS!       1
...                                                  ...     ...
34727                               💰法拉盛中心Private Studio       1
34728                🔹️Charming🔹️1br near Airtran & LIRR       1
34729                                  😎Bedstuy is fly 😎       1
34730  🥂 AMAZING STUDIO IN CHINATOWN | 🚇 CLOSE TO SUBWAY       1
34731  🪴🛋🌞 Unique sunny clean brownstone studio 1st f...       1

[34732 rows x 2 columns]

In [10]:
#b) Los registros de los host que se hallan unido a Airbnb “despues del año 2020”
filtro1=df[df["host_since"]>"2020-12-31"]
filtro1

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
3116,6422511,https://www.airbnb.com/rooms/6422511,20250617032754,2025-06-17,city scrape,My Little Guest Apartment,"Rustic little two bedroom apartment, on the fi...",The neighborhood is mostly Asian. Plenty of pl...,https://a0.muscache.com/pictures/hosting/Hosti...,493949425,...,4.90,4.63,4.79,OSE-STRREG-0000469,f,1,0,1,0,2.97
3282,6660518,https://www.airbnb.com/rooms/6660518,20250617032754,2025-06-17,city scrape,Brooklyn Vibes in Queens - Stylish Penthouse S...,"We are two respectful, fun and young professio...","Kew Gardens has many locally-owned businesses,...",https://a0.muscache.com/pictures/93468da6-eb7f...,540633390,...,4.92,4.88,4.92,NaN,f,4,1,3,0,0.22
3425,7177666,https://www.airbnb.com/rooms/7177666,20250617032754,2025-06-17,city scrape,Beautiful Brooklyn Home w/Backyard Garden,Two story modern home w/ private backyard. Gre...,"As Brooklyn's most sought-after neighborhood, ...",https://a0.muscache.com/pictures/25824f3b-ea15...,686665034,...,4.97,4.85,4.68,NaN,f,1,1,0,0,0.29
4957,9757875,https://www.airbnb.com/rooms/9757875,20250617032754,2025-06-17,city scrape,Queens' Loft - Stylish Penthouse & Patio Share,"We are two respectful, fun and young professio...","Kew Gardens has many locally-owned businesses,...",https://a0.muscache.com/pictures/ad583944-2ba5...,540633390,...,4.67,4.53,4.13,NaN,f,4,1,3,0,0.13
5807,12039579,https://www.airbnb.com/rooms/12039579,20250617032754,2025-06-17,city scrape,Manhattan Elegance in Queens - Penthouse Share!,Queens NYC SHARE - Master BR aka. Manhattan ro...,"Kew Gardens has many locally-owned businesses,...",https://a0.muscache.com/pictures/797a29f7-16d6...,540633390,...,4.93,4.93,4.86,NaN,f,4,1,3,0,0.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36302,1442915323206687126,https://www.airbnb.com/rooms/1442915323206687126,20250617032754,2025-06-17,city scrape,Renovated 1BD Apt in the UES,Fully Furnished 1 Bedroom on the Upper East Si...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,458591926,...,NaN,NaN,NaN,NaN,f,11,11,0,0,NaN
36303,1442921529052314599,https://www.airbnb.com/rooms/1442921529052314599,20250617032754,2025-06-17,city scrape,Clinton Duplex | Art-filled 2BR Duplex w/Yard,"Welcome to Clinton Duplex, a beautifully-desig...",NaN,https://a0.muscache.com/pictures/prohost-api/H...,700261290,...,NaN,NaN,NaN,NaN,f,4,4,0,0,NaN
36307,1443471896307371963,https://www.airbnb.com/rooms/1443471896307371963,20250617032754,2025-06-17,city scrape,Luxury Studio Near Prospect Park,July–August Sublet | Flexible Dates<br />Moder...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,650439003,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
36317,1444361816139266163,https://www.airbnb.com/rooms/1444361816139266163,20250617032754,2025-06-17,city scrape,Soho LES,Book this centrally located home for groups an...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,408918750,...,NaN,NaN,NaN,NaN,t,4,4,0,0,NaN
36320,1444497972042807274,https://www.airbnb.com/rooms/1444497972042807274,20250617032754,2025-06-17,city scrape,"Steps from the Empire State, Iconic Views, 2 Beds",Welcome to your dream Manhattan escape — a stu...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,677540330,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN

In [18]:
revision2 = filtro1.groupby("host_since").size().reset_index(name='counts')
revision2

      host_since  counts
0     2021-01-01       2
1     2021-01-02       9
2     2021-01-03       1
3     2021-01-04       4
4     2021-01-05       3
...          ...     ...
1305  2025-06-04       1
1306  2025-06-05       2
1307  2025-06-06       1
1308  2025-06-09       5
1309  2025-06-10       1

[1310 rows x 2 columns]

In [12]:
#c) Los registros de los host que responden “a más tardar en 1 día”
filtro2=df[~(df["host_response_time"] == "a few days or more")]
filtro2

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2539,https://www.airbnb.com/rooms/2539,20250617032754,2025-06-17,city scrape,Superfast Wi-Fi. Clean & quiet home by the park,"Bright, serene room in a renovated apartment h...",Close to Prospect Park and Historic Ditmas Park,https://a0.muscache.com/pictures/hosting/Hosti...,2787,...,5.0,4.75,4.88,NaN,f,6,1,5,0,0.08
1,2595,https://www.airbnb.com/rooms/2595,20250617032754,2025-06-17,city scrape,Skylit Midtown Manhattan Spacious Studio,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,https://a0.muscache.com/pictures/hosting/Hosti...,2845,...,4.8,4.81,4.40,NaN,f,3,3,0,0,0.26
2,5136,https://www.airbnb.com/rooms/5136,20250617032754,2025-06-17,city scrape,Spacious Family Friendly Duplex w/ Patio + Yard,"We welcome you to stay in our lovely 2 br, 130...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,7378,...,5.0,4.75,4.75,NaN,t,1,1,0,0,0.03
3,6848,https://www.airbnb.com/rooms/6848,20250617032754,2025-06-17,city scrape,Only 2 stops to Manhattan studio,Comfortable studio apartment with super comfor...,NaN,https://a0.muscache.com/pictures/e4f031a7-f146...,15991,...,4.8,4.69,4.58,NaN,f,1,1,0,0,1.00
4,6872,https://www.airbnb.com/rooms/6872,20250617032754,2025-06-17,previous scrape,Uptown Sanctuary w/ Private Bath (Month to Month),This charming distancing-friendly month-to-mon...,This sweet Harlem sanctuary is a 10-20 minute ...,https://a0.muscache.com/pictures/miso/Hosting-...,16104,...,5.0,5.00,5.00,NaN,f,2,0,2,0,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36317,1444361816139266163,https://www.airbnb.com/rooms/1444361816139266163,20250617032754,2025-06-17,city scrape,Soho LES,Book this centrally located home for groups an...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,408918750,...,NaN,NaN,NaN,NaN,t,4,4,0,0,NaN
36318,1444367137899199563,https://www.airbnb.com/rooms/1444367137899199563,20250617032754,2025-06-17,city scrape,Park & Pool Adjacent Loft Studio,"Situated next to Brooklyn Navy Yard, between D...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,2076525,...,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN
36319,1444466789913170608,https://www.airbnb.com/rooms/1444466789913170608,20250617032754,2025-06-17,city scrape,"Peaceful Room, Big Comfy Bed","Peaceful, sunlit bedroom in a friendly, tree-t...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,42088828,...,NaN,NaN,NaN,NaN,f,2,0,2,0,NaN
36320,1444497972042807274,https://www.airbnb.com/rooms/1444497972042807274,20250617032754,2025-06-17,city scrape,"Steps from the Empire State, Iconic Views, 2 Beds",Welcome to your dream Manhattan escape — a stu...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,677540330,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
36321,1444533606768940303,https://www.airbnb.com/rooms/1444533606768940303,20250617032754,2025-06-17,city scrape,2BR/Brooklyn: Private Backyard,Spacious 2BR Brooklyn home in beautiful Bed-St...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,10931359,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [17]:
revision3 = filtro2.groupby("host_response_time").size().reset_index(name='counts')
revision3

   host_response_time  counts
0        within a day    2126
1  within a few hours    4710
2      within an hour   13307

In [29]:
#d) Los registros de las filas “Múltiplos de 200… (400, 600, 800, etc.)”
filtro3 = df.iloc[df.index[df.index % 200 == 0]]
print("Filas múltiplos de 200:")
print(filtro3)

Filas múltiplos de 200:
                        id                                       listing_url  \
0                     2539                 https://www.airbnb.com/rooms/2539
200                 235960               https://www.airbnb.com/rooms/235960
400                 432090               https://www.airbnb.com/rooms/432090
600                 704838               https://www.airbnb.com/rooms/704838
800                 880424               https://www.airbnb.com/rooms/880424
...                    ...                                               ...
35400  1385932425735867189  https://www.airbnb.com/rooms/1385932425735867189
35600  1399585901077219028  https://www.airbnb.com/rooms/1399585901077219028
35800  1405859861441804816  https://www.airbnb.com/rooms/1405859861441804816
36000  1420316312079828057  https://www.airbnb.com/rooms/1420316312079828057
36200  1425422257530079509  https://www.airbnb.com/rooms/1425422257530079509

            scrape_id last_scraped           source  \
0      20250617032754   2025-06-17      city scrape
200    20250617032754   2025-06-17      city scrape
400    20250617032754   2025-06-17  previous scrape
600    20250617032754   2025-06-17      city scrape
800    20250617032754   2025-06-17  previous scrape
...               ...          ...              ...
35400  20250617032754   2025-06-17      city scrape
35600  20250617032754   2025-06-17      city scrape
35800  20250617032754   2025-06-17      city scrape
36000  20250617032754   2025-06-17      city scrape
36200  20250617032754   2025-06-17      city scrape

                                                   name  \
0      Superfast Wi-Fi.  Clean & quiet home by the park
200           LES private 1 bd apt, walk to *everthing*
400                           Only 5 Min. to Manhattan!
600                        An Oasis in  the Big Apple 1
800                     ★Beautiful Home Away From Home★
...                                                 ...
35400          King Great View at Public Hotel New York
35600                     Sunny French Door Room in UES
35800                      403-3C NEW renovated 3br UES
36000                  Stylish Apt in Heart of Brooklyn
36200           Luxurious home in charming UWS (30day+)

                                             description  \
0      Bright, serene room in a renovated apartment h...
200    How would you like to stay in Lady Gaga's old ...
400    Comfortable room in cozy New York apartment. N...
600                                                  NaN
800    Welcome to our apartment! From our guests:<br ...
...                                                  ...
35400  Experience the luxe life in New York's center!...
35600  Just a quick walk a 25 min train ride to China...
35800  This beautifully renovated 3-bedroom apartment...
36000  Modern 2BR/2BA Brooklyn retreat with skylights...
36200  Welcome! Perfect for families or professionals...

                                   neighborhood_overview  \
0        Close to Prospect Park and Historic Ditmas Park
200    This clean 1 bedroom, 2nd floor apartment is i...
400    Neighborhood is very nice, SAFE, and convenien...
600                                                  NaN
800    I love my neighborhood. It's inspiringly diver...
...                                                  ...
35400  - Color Factory NYC Interactive Art Museum - 1...
35600                                                NaN
35800                                                NaN
36000                                                NaN
36200                                                NaN

                                             picture_url    host_id  ...  \
0      https://a0.muscache.com/pictures/hosting/Hosti...       2787  ...
200    https://a0.muscache.com/pictures/miso/Hosting-...    1236817  ...
400    https://a0.muscache.com/pictures/6aedec9b-f746...    2148881  ...
600    https://a0.muscache.com/pictures/4b022ab3-4c6a...    3621183  ...
800    https://a0.muscache.com/pictures/6a2af88e-3691...    3549531  ...
...                                                  ...        ...  ...
35400  https://a0.muscache.com/pictures/prohost-api/H...  501999278  ...
35600  https://a0.muscache.com/pictures/hosting/Hosti...   12264492  ...
35800  https://a0.muscache.com/pictures/miso/Hosting-...   27181542  ...
36000  https://a0.muscache.com/pictures/hosting/Hosti...  194712417  ...
36200  https://a0.muscache.com/pictures/hosting/Hosti...    2163745  ...

      review_scores_communication review_scores_location review_scores_value  \
0                            5.00                   4.75                4.88
200                          4.91                   4.82                4.48
400                          4.93                   4.84                4.81
600                          4.79                   4.75                4.65
800                          4.96                   4.69                4.89
...                           ...                    ...                 ...
35400                         NaN                    NaN                 NaN
35600                        4.00                   5.00                5.00
35800                         NaN                    NaN                 NaN
36000                         NaN                    NaN                 NaN
36200                         NaN                    NaN                 NaN

      license instant_bookable calculated_host_listings_count  \
0         NaN                f                              6
200       NaN                f                              1
400       NaN                f                              1
600       NaN                f                              3
800       NaN                f                              1
...       ...              ...                            ...
35400  Exempt                t                            157
35600     NaN                f                              3
35800     NaN                f                             85
36000     NaN                f                              1
36200     NaN                f                              1

      calculated_host_listings_count_entire_homes  \
0                                               1
200                                             1
400                                             0
600                                             3
800                                             0
...                                           ...
35400                                           0
35600                                           1
35800                                          85
36000                                           1
36200                                           1

      calculated_host_listings_count_private_rooms  \
0                                                5
200                                              0
400                                              1
600                                              0
800                                              1
...                                            ...
35400                                            6
35600                                            2
35800                                            0
36000                                            0
36200                                            0

      calculated_host_listings_count_shared_rooms reviews_per_month
0                                               0              0.08
200                                             0              0.73
400                                             0              0.43
600                                             0              0.88
800                                             0              0.84
...                                           ...               ...
35400                                           0               NaN
35600                                           0              0.57
35800                                           0               NaN
36000                                           0               NaN
36200                                           0               NaN

[182 rows x 79 columns]

In [44]:
revision4 = df.loc[(df.index % 200 == 0) & (df.index != 0)]
print("indices seleccionados:", revision4.index.tolist())

indices seleccionados: [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000, 3200, 3400, 3600, 3800, 4000, 4200, 4400, 4600, 4800, 5000, 5200, 5400, 5600, 5800, 6000, 6200, 6400, 6600, 6800, 7000, 7200, 7400, 7600, 7800, 8000, 8200, 8400, 8600, 8800, 9000, 9200, 9400, 9600, 9800, 10000, 10200, 10400, 10600, 10800, 11000, 11200, 11400, 11600, 11800, 12000, 12200, 12400, 12600, 12800, 13000, 13200, 13400, 13600, 13800, 14000, 14200, 14400, 14600, 14800, 15000, 15200, 15400, 15600, 15800, 16000, 16200, 16400, 16600, 16800, 17000, 17200, 17400, 17600, 17800, 18000, 18200, 18400, 18600, 18800, 19000, 19200, 19400, 19600, 19800, 20000, 20200, 20400, 20600, 20800, 21000, 21200, 21400, 21600, 21800, 22000, 22200, 22400, 22600, 22800, 23000, 23200, 23400, 23600, 23800, 24000, 24200, 24400, 24600, 24800, 25000, 25200, 25400, 25600, 25800, 26000, 26200, 26400, 26600, 26800, 27000, 27200, 27400, 27600, 27800, 28000, 28200, 28400, 28600, 28800, 29000, 29200, 29400, 29600, 29800, 30000, 30200, 30400, 30600, 30800, 31000, 31200, 31400, 31600, 31800, 32000, 32200, 32400, 32600, 32800, 33000, 33200, 33400, 33600, 33800, 34000, 34200, 34400, 34600, 34800, 35000, 35200, 35400, 35600, 35800, 36000, 36200]

In [21]:
#e) Los registros de los tipos de cuarto: “Entire home”  y “Private room”
filtro4=df[(df["beds"] <= 4)]
filtro4

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2539,https://www.airbnb.com/rooms/2539,20250617032754,2025-06-17,city scrape,Superfast Wi-Fi. Clean & quiet home by the park,"Bright, serene room in a renovated apartment h...",Close to Prospect Park and Historic Ditmas Park,https://a0.muscache.com/pictures/hosting/Hosti...,2787,...,5.00,4.75,4.88,NaN,f,6,1,5,0,0.08
1,2595,https://www.airbnb.com/rooms/2595,20250617032754,2025-06-17,city scrape,Skylit Midtown Manhattan Spacious Studio,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,https://a0.muscache.com/pictures/hosting/Hosti...,2845,...,4.80,4.81,4.40,NaN,f,3,3,0,0,0.26
2,5136,https://www.airbnb.com/rooms/5136,20250617032754,2025-06-17,city scrape,Spacious Family Friendly Duplex w/ Patio + Yard,"We welcome you to stay in our lovely 2 br, 130...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,7378,...,5.00,4.75,4.75,NaN,t,1,1,0,0,0.03
3,6848,https://www.airbnb.com/rooms/6848,20250617032754,2025-06-17,city scrape,Only 2 stops to Manhattan studio,Comfortable studio apartment with super comfor...,NaN,https://a0.muscache.com/pictures/e4f031a7-f146...,15991,...,4.80,4.69,4.58,NaN,f,1,1,0,0,1.00
5,6990,https://www.airbnb.com/rooms/6990,20250617032754,2025-06-17,city scrape,UES Beautiful Blue Room,Beautiful peaceful healthy home,"Location: Five minutes to Central Park, Museum...",https://a0.muscache.com/pictures/45fb4ec7-6856...,16800,...,4.94,4.85,4.83,NaN,f,1,0,1,0,1.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36317,1444361816139266163,https://www.airbnb.com/rooms/1444361816139266163,20250617032754,2025-06-17,city scrape,Soho LES,Book this centrally located home for groups an...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,408918750,...,NaN,NaN,NaN,NaN,t,4,4,0,0,NaN
36318,1444367137899199563,https://www.airbnb.com/rooms/1444367137899199563,20250617032754,2025-06-17,city scrape,Park & Pool Adjacent Loft Studio,"Situated next to Brooklyn Navy Yard, between D...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,2076525,...,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN
36319,1444466789913170608,https://www.airbnb.com/rooms/1444466789913170608,20250617032754,2025-06-17,city scrape,"Peaceful Room, Big Comfy Bed","Peaceful, sunlit bedroom in a friendly, tree-t...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,42088828,...,NaN,NaN,NaN,NaN,f,2,0,2,0,NaN
36320,1444497972042807274,https://www.airbnb.com/rooms/1444497972042807274,20250617032754,2025-06-17,city scrape,"Steps from the Empire State, Iconic Views, 2 Beds",Welcome to your dream Manhattan escape — a stu...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,677540330,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
36321,1444533606768940303,https://www.airbnb.com/rooms/1444533606768940303,20250617032754,2025-06-17,city scrape,2BR/Brooklyn: Private Backyard,Spacious 2BR Brooklyn home in beautiful Bed-St...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,10931359,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [22]:
revision5=filtro4.groupby("beds").size().reset_index(name='counts')
revision5

   beds  counts
0   0.0     571
1   1.0   12807
2   2.0    4946
3   3.0    1806
4   4.0     866

In [23]:
#f) Los registros que “a lo mucho cuenten con 4 camas” 
filtro5=df[df["beds"] <= 4]
filtro5

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2539,https://www.airbnb.com/rooms/2539,20250617032754,2025-06-17,city scrape,Superfast Wi-Fi. Clean & quiet home by the park,"Bright, serene room in a renovated apartment h...",Close to Prospect Park and Historic Ditmas Park,https://a0.muscache.com/pictures/hosting/Hosti...,2787,...,5.00,4.75,4.88,NaN,f,6,1,5,0,0.08
1,2595,https://www.airbnb.com/rooms/2595,20250617032754,2025-06-17,city scrape,Skylit Midtown Manhattan Spacious Studio,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,https://a0.muscache.com/pictures/hosting/Hosti...,2845,...,4.80,4.81,4.40,NaN,f,3,3,0,0,0.26
2,5136,https://www.airbnb.com/rooms/5136,20250617032754,2025-06-17,city scrape,Spacious Family Friendly Duplex w/ Patio + Yard,"We welcome you to stay in our lovely 2 br, 130...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,7378,...,5.00,4.75,4.75,NaN,t,1,1,0,0,0.03
3,6848,https://www.airbnb.com/rooms/6848,20250617032754,2025-06-17,city scrape,Only 2 stops to Manhattan studio,Comfortable studio apartment with super comfor...,NaN,https://a0.muscache.com/pictures/e4f031a7-f146...,15991,...,4.80,4.69,4.58,NaN,f,1,1,0,0,1.00
5,6990,https://www.airbnb.com/rooms/6990,20250617032754,2025-06-17,city scrape,UES Beautiful Blue Room,Beautiful peaceful healthy home,"Location: Five minutes to Central Park, Museum...",https://a0.muscache.com/pictures/45fb4ec7-6856...,16800,...,4.94,4.85,4.83,NaN,f,1,0,1,0,1.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36317,1444361816139266163,https://www.airbnb.com/rooms/1444361816139266163,20250617032754,2025-06-17,city scrape,Soho LES,Book this centrally located home for groups an...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,408918750,...,NaN,NaN,NaN,NaN,t,4,4,0,0,NaN
36318,1444367137899199563,https://www.airbnb.com/rooms/1444367137899199563,20250617032754,2025-06-17,city scrape,Park & Pool Adjacent Loft Studio,"Situated next to Brooklyn Navy Yard, between D...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,2076525,...,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN
36319,1444466789913170608,https://www.airbnb.com/rooms/1444466789913170608,20250617032754,2025-06-17,city scrape,"Peaceful Room, Big Comfy Bed","Peaceful, sunlit bedroom in a friendly, tree-t...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,42088828,...,NaN,NaN,NaN,NaN,f,2,0,2,0,NaN
36320,1444497972042807274,https://www.airbnb.com/rooms/1444497972042807274,20250617032754,2025-06-17,city scrape,"Steps from the Empire State, Iconic Views, 2 Beds",Welcome to your dream Manhattan escape — a stu...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,677540330,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
36321,1444533606768940303,https://www.airbnb.com/rooms/1444533606768940303,20250617032754,2025-06-17,city scrape,2BR/Brooklyn: Private Backyard,Spacious 2BR Brooklyn home in beautiful Bed-St...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,10931359,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [24]:
revision6=filtro5.groupby("beds").size().reset_index(name='counts')
revision6

   beds  counts
0   0.0     571
1   1.0   12807
2   2.0    4946
3   3.0    1806
4   4.0     866

In [25]:
#g) Los registros que “sean superhost”
filtro6 = df[df["host_is_superhost"] == "t"]
filtro6

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
3,6848,https://www.airbnb.com/rooms/6848,20250617032754,2025-06-17,city scrape,Only 2 stops to Manhattan studio,Comfortable studio apartment with super comfor...,NaN,https://a0.muscache.com/pictures/e4f031a7-f146...,15991,...,4.80,4.69,4.58,NaN,f,1,1,0,0,1.00
7,7097,https://www.airbnb.com/rooms/7097,20250617032754,2025-06-17,city scrape,"Perfect for Your Parents, With Garden & Patio",Parents/grandparents coming to town or are you...,"Residential, village-like atmosphere. Lots of ...",https://a0.muscache.com/pictures/aaac19fc-4b4d...,17571,...,4.93,4.95,4.82,OSE-STRREG-0000008,t,2,0,2,0,2.20
11,60611,https://www.airbnb.com/rooms/60611,20250617032754,2025-06-17,city scrape,SpaHa Studio Monthly Rental,This is the real New York City experience: exp...,Our neighborhood is quite safe and everyone ta...,https://a0.muscache.com/pictures/ad70dcaf-4ec7...,292204,...,4.98,4.60,4.80,NaN,f,4,4,0,0,1.14
14,60680,https://www.airbnb.com/rooms/60680,20250617032754,2025-06-17,city scrape,"Bright, High Ceiling, Spacious & Cozy 1BR - En...",You will have this entire 1 bedroom apartment ...,"My neighborhood is a safe, residential neighbo...",https://a0.muscache.com/pictures/hosting/Hosti...,292630,...,4.84,4.84,4.42,NaN,t,6,5,1,0,0.95
17,7801,https://www.airbnb.com/rooms/7801,20250617032754,2025-06-17,city scrape,Sunny Williamsburg Loft with Sauna,A huge loft in a repurposed factory building i...,We've lived here for over 15 years and love Wi...,https://a0.muscache.com/pictures/miso/Hosting-...,21207,...,4.78,5.00,4.89,NaN,f,1,1,0,0,0.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36302,1442915323206687126,https://www.airbnb.com/rooms/1442915323206687126,20250617032754,2025-06-17,city scrape,Renovated 1BD Apt in the UES,Fully Furnished 1 Bedroom on the Upper East Si...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,458591926,...,NaN,NaN,NaN,NaN,f,11,11,0,0,NaN
36304,1442991173721928785,https://www.airbnb.com/rooms/1442991173721928785,20250617032754,2025-06-17,city scrape,Gym+Desk+Wardrobe+Laundry+Subway,Everything you need included to feel like home...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,332212831,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
36313,1443702761828456737,https://www.airbnb.com/rooms/1443702761828456737,20250617032754,2025-06-17,city scrape,*Urban Oasis in Eclectic Astoria 5 minutes to ...,Discover your perfect NYC retreat in this char...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,157832521,...,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN
36314,1443726687163433447,https://www.airbnb.com/rooms/1443726687163433447,20250617032754,2025-06-17,city scrape,Harlem Muse,"Quiet, clean building on a cozy, historic Har...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,18999923,...,NaN,NaN,NaN,NaN,f,4,4,0,0,NaN
36316,1444331236457245805,https://www.airbnb.com/rooms/1444331236457245805,20250617032754,2025-06-17,city scrape,Central Park Studio,Enjoy easy access to everything from this perf...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,8178950,...,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN

In [26]:
revision7=filtro6.groupby("host_is_superhost").size().reset_index(name='counts')
revision7

  host_is_superhost  counts
0                 t    6576

In [27]:
#h) Los registros de las columnas “impares”
filtro7 = df.iloc[:, 1::2]
filtro7

,listing_url,last_scraped,name,neighborhood_overview,host_id,host_name,host_location,host_response_time,host_acceptance_rate,host_thumbnail_url,...,availability_eoy,estimated_occupancy_l365d,first_review,review_scores_rating,review_scores_cleanliness,review_scores_communication,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_shared_rooms
0,https://www.airbnb.com/rooms/2539,2025-06-17,Superfast Wi-Fi. Clean & quiet home by the park,Close to Prospect Park and Historic Ditmas Park,2787,John,"New York, NY",within a few hours,80%,https://a0.muscache.com/im/pictures/user/User/...,...,180,0,2015-12-04,4.89,5.00,5.0,4.88,f,1,0
1,https://www.airbnb.com/rooms/2595,2025-06-17,Skylit Midtown Manhattan Spacious Studio,Centrally located in the heart of Manhattan ju...,2845,Jennifer,"Woodstock, NY",within a few hours,24%,https://a0.muscache.com/im/pictures/user/50fc5...,...,145,0,2009-11-21,4.68,4.63,4.8,4.40,f,3,0
2,https://www.airbnb.com/rooms/5136,2025-06-17,Spacious Family Friendly Duplex w/ Patio + Yard,NaN,7378,Rebecca,"New York, NY",NaN,100%,https://a0.muscache.com/im/users/7378/profile_...,...,80,0,2014-01-02,4.75,4.50,5.0,4.75,t,1,0
3,https://www.airbnb.com/rooms/6848,2025-06-17,Only 2 stops to Manhattan studio,NaN,15991,Allen,"New York, NY",within an hour,100%,https://a0.muscache.com/im/users/15991/profile...,...,52,240,2009-05-25,4.59,4.85,4.8,4.58,f,1,0
4,https://www.airbnb.com/rooms/6872,2025-06-17,Uptown Sanctuary w/ Private Bath (Month to Month),This sweet Harlem sanctuary is a 10-20 minute ...,16104,Kahshanna,"New York, NY",within a day,33%,https://a0.muscache.com/im/pictures/user/d865a...,...,2,0,2022-06-05,5.00,5.00,5.0,5.00,f,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36317,https://www.airbnb.com/rooms/1444361816139266163,2025-06-17,Soho LES,NaN,408918750,Henery,NaN,within an hour,80%,https://a0.muscache.com/defaults/user_pic-50x5...,...,194,0,NaN,NaN,NaN,NaN,NaN,t,4,0
36318,https://www.airbnb.com/rooms/1444367137899199563,2025-06-17,Park & Pool Adjacent Loft Studio,NaN,2076525,Douglas,"New York, United States",NaN,NaN,https://a0.muscache.com/im/users/2076525/profi...,...,118,0,NaN,NaN,NaN,NaN,NaN,t,1,0
36319,https://www.airbnb.com/rooms/1444466789913170608,2025-06-17,"Peaceful Room, Big Comfy Bed",NaN,42088828,Jack,"New York, NY",within an hour,50%,https://a0.muscache.com/im/pictures/user/User/...,...,171,0,NaN,NaN,NaN,NaN,NaN,f,0,0
36320,https://www.airbnb.com/rooms/1444497972042807274,2025-06-17,"Steps from the Empire State, Iconic Views, 2 Beds",NaN,677540330,Marina,NaN,within an hour,100%,https://a0.muscache.com/im/pictures/user/User/...,...,180,0,NaN,NaN,NaN,NaN,NaN,f,2,0
36321,https://www.airbnb.com/rooms/1444533606768940303,2025-06-17,2BR/Brooklyn: Private Backyard,NaN,10931359,Obinna,"Los Angeles, CA",NaN,NaN,https://a0.muscache.com/im/pictures/user/54dbc...,...,36,0,NaN,NaN,NaN,NaN,NaN,f,1,0

In [28]:
revision8 = filtro7.groupby(filtro7.columns[0]).size().reset_index(name='counts')
revision8

                                            listing_url  counts
0                 https://www.airbnb.com/rooms/10000070       1
1                   https://www.airbnb.com/rooms/100002       1
2      https://www.airbnb.com/rooms/1000023148920376325       1
3      https://www.airbnb.com/rooms/1000041661179181846       1
4                 https://www.airbnb.com/rooms/10001022       1
...                                                 ...     ...
36317   https://www.airbnb.com/rooms/999867862236982436       1
36318              https://www.airbnb.com/rooms/9998930       1
36319              https://www.airbnb.com/rooms/9999220       1
36320              https://www.airbnb.com/rooms/9999252       1
36321   https://www.airbnb.com/rooms/999964466102080007       1

[36322 rows x 2 columns]

In [31]:
#Convertir archivo filtrado a CSV
filtro.to_csv("ACt2.2.csv")
filtro1.to_csv("ACt2_2.csv")
filtro2.to_csv("ACt2.2clase.csv")
filtro3.to_csv("ACt2.2cl.csv")
filtro4.to_csv("ACt.2.2.csv")
filtro5.to_csv("ACtiv_2.2csv")
filtro6.to_csv("ACt_2.2.csv")
filtro7.to_csv("ACti_2.2.csv")